info:
  name: 用户中心
  contact: 动脑学院VIP

server:
  port: 9004
spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${mysql_host}:3306/uaa-db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${mysql_username}
    password: ${mysql_password}
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          # 自动创建表
          auto: update
    
